
server:
  port: 8080

spring:
  application:
    name: crm

  datasource:
    url: jdbc:mysql://localhost:3306/crm_db
    username: root
    password: asif

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true